// Golden plans over committed traces.
//
// Spec section 90. The point is not that these digests are correct in some absolute sense --
// it is that a change to any planner shows up as a failing CPU test rather than as a
// different number in a benchmark somebody runs a week later. When a digest here changes,
// either the change was intended and the golden file moves with it in the same commit, or it
// was not and this is the only thing that would have caught it.
//
// The traces are committed rather than generated at test time. A golden test whose fixture
// is regenerated by the code under test asserts nothing.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "tensortransit/ceiling.h"
#include "tensortransit/planner.h"
#include "tensortransit/trace.h"

using namespace tensortransit;

#ifndef TENSORTRANSIT_GOLDEN_DIR
#define TENSORTRANSIT_GOLDEN_DIR "tests/golden"
#endif

static int g_failures = 0;
#define CHECK(cond) do { if (!(cond)) { \
    std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); ++g_failures; } } while (0)

static std::string golden_path(const char* name) {
    return std::string(TENSORTRANSIT_GOLDEN_DIR) + "/" + name;
}

struct Loaded {
    TensorRegistry registry;
    TransitGraph graph;
    TraceMetadata meta;
    bool ok = false;
};

static Loaded load(const char* name) {
    Loaded out;
    std::string error;
    out.ok = read_trace_file(golden_path(name), &out.registry, &out.graph, &out.meta, &error);
    if (!out.ok) std::printf("FAIL cannot read %s: %s\n", name, error.c_str());
    return out;
}

static TransitPlannerConfig base() {
    // Pinned deliberately. A golden digest computed under whatever the defaults happen to be
    // would change whenever a default changed, which is a different fact from the one this
    // file is asserting.
    TransitPlannerConfig config{};
    config.persist_roles = RoleMask::of(TensorRole::RecurrentState, TensorRole::KVCache);
    // NOT stream_roles. `preset_config` gives those to the GLOBAL arm alone, because telling
    // the weight stream to get out of the way is a coordination action and an arm that could
    // take it would not be the independent policy it is supposed to be. Setting it in the
    // base handed it to every arm, which was invisible only while Stream was unreachable
    // under a cyclic decode graph -- so the harness and the design agreed by accident.
    config.prefetch_roles = RoleMask::none();
    config.prefetch_enabled = false;
    config.budget_fraction = 0.75;
    config.hit_ratio = 0.70;
    config.min_hit_ratio = 0.05;
    config.role_floor_share = 0.25;
    config.reuse_metric = ReuseMetric::Bytes;
    config.admission = AdmissionRule::Density;
    config.window_binding = WindowBinding::PerConsumer;
    // Pinned for the same reason as everything else here: the cost model decides what a plan
    // is predicted to be worth, and one admission rule -- Survival -- decides USING that
    // price, so an unpinned default would move these digests for a reason this file is not
    // about.
    config.cost_model = CostModel::Residency;
    return config;
}

// name -> digest, one "trace/arm 0x..." per line. Missing file means "record", which is how
// a new trace is added; a mismatch is always a failure.
static std::map<std::string, std::string> read_expected() {
    std::map<std::string, std::string> out;
    std::ifstream file(golden_path("plans.golden"));
    if (!file) return out;
    std::string key, value;
    while (file >> key >> value) out[key] = value;
    return out;
}

int main(int argc, char** argv) {
    const bool record = argc > 1 && std::strcmp(argv[1], "--record") == 0;
    const std::map<std::string, std::string> expected = read_expected();
    std::ostringstream recorded;

    const char* traces[] = {"trace_recurrent.json", "trace_recurrent_kv.json",
                            "trace_concurrency.json"};
    DeviceProfile device{};
    CHECK(device_profile_by_name("rtx5090", &device));

    for (const char* trace_name : traces) {
        Loaded loaded = load(trace_name);
        if (!loaded.ok) { ++g_failures; continue; }
        CHECK(loaded.graph.validate() == nullptr);
        // A trace whose uses name tensors it does not declare would silently shrink the
        // graph, and every digest below would be a digest of the wrong workload.
        CHECK(loaded.graph.unresolved_uses() == 0);

        RuntimeState state{};
        state.active_requests = loaded.meta.active_requests;
        parse_runtime_phase(loaded.meta.phase.c_str(), &state.phase);
        PlanInput input{&loaded.graph, &loaded.registry, device, state};

        for (const PolicyPreset preset :
             {PolicyPreset::Baseline, PolicyPreset::RecurrentOnly, PolicyPreset::KVOnly,
              PolicyPreset::NaiveBothPersistent, PolicyPreset::Global}) {
            const TransitPlannerConfig config = preset_config(preset, base());
            auto planner = make_planner(preset_planner(preset), config);
            if (!planner) { ++g_failures; continue; }
            TransitPlan plan = planner->build_plan(input);
            plan.finalize();

            const char* problem = plan.validate();
            if (problem) std::printf("FAIL %s/%s: %s\n", trace_name, to_string(preset), problem);
            CHECK(problem == nullptr);

            char digest[32];
            std::snprintf(digest, sizeof(digest), "%016llx",
                          static_cast<unsigned long long>(plan.digest()));
            const std::string key = std::string(trace_name) + "/" + to_string(preset);
            recorded << key << " " << digest << "\n";

            const auto it = expected.find(key);
            if (it == expected.end()) {
                if (!record) {
                    std::printf("FAIL no golden digest for %s (run with --record to add it)\n",
                                key.c_str());
                    ++g_failures;
                }
            } else if (it->second != digest) {
                std::printf("FAIL %s: plan changed, golden %s but got %s\n", key.c_str(),
                            it->second.c_str(), digest);
                ++g_failures;
            }
        }

        // The graph's own arithmetic is golden too, and it is the part a planner change must
        // NOT move: a planner that altered the recorded step traffic would be rewriting the
        // denominator of its own score.
        char key[128];
        std::snprintf(key, sizeof(key), "%s/step_traffic_bytes", trace_name);
        char value[32];
        std::snprintf(value, sizeof(value), "%zu", loaded.graph.step_traffic_bytes());
        recorded << key << " " << value << "\n";
        const auto it = expected.find(key);
        if (it != expected.end()) {
            if (it->second != value) {
                std::printf("FAIL %s: step traffic changed, golden %s but got %s\n", key,
                            it->second.c_str(), value);
                ++g_failures;
            }
        } else if (!record) {
            std::printf("FAIL no golden step traffic for %s\n", key);
            ++g_failures;
        }
    }

    // The one arithmetic identity worth pinning by hand, because it is the number the whole
    // project turns on and it is checkable against a figure published before any of this
    // code existed: on Qwen3.8-27B at batch 1, a persisting policy over recurrent state has
    // a ceiling of 0.68% and holds 41% of the footprint. See README, "Concurrency is where
    // the room is". If the graph ever stops reproducing that, the graph is wrong.
    {
        Loaded loaded = load("trace_recurrent.json");
        if (loaded.ok) {
            const CeilingReport report =
                compute_ceiling(loaded.graph, device, RoleMask::of(TensorRole::RecurrentState));
            const double ceiling_percent = (report.bounded_ratio() - 1.0) * 100.0;
            const double resident = report.resident_fraction();
            std::printf("  recurrent persist ceiling %.3f%% at %.1f%% residency"
                        " (published: 0.68%% at 41%%)\n",
                        ceiling_percent, resident * 100.0);
            CHECK(ceiling_percent > 0.66 && ceiling_percent < 0.70);
            CHECK(resident > 0.40 && resident < 0.42);
            // ...and the traffic ceiling, published as 1.69%.
            const double traffic_percent = (report.removable_ratio() - 1.0) * 100.0;
            CHECK(traffic_percent > 1.67 && traffic_percent < 1.71);
        } else {
            ++g_failures;
        }
    }

    if (record) {
        std::ofstream file(golden_path("plans.golden"));
        file << recorded.str();
        std::printf("recorded %s\n", golden_path("plans.golden").c_str());
        return 0;
    }
    if (g_failures) { std::cout << g_failures << " golden check(s) failed\n"; return 1; }
    std::cout << "golden plan tests passed\n";
    return 0;
}
