// Golden plans over committed traces.
//
// Spec section 90. The point is not that these digests are correct in some absolute sense --
// it is that a change to any planner shows up as a failing CPU test rather than as a
// different number in a benchmark somebody runs a week later. When a digest here changes,
// either the change was intended and the golden file moves with it in the same commit, or it
// was not and this is the only thing that would have caught it.
//
// The traces are committed rather than generated at test time. A golden test whose fixture
// is regenerated by the code under test asserts nothing.
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "tensortransit/ceiling.h"
#include "tensortransit/planner.h"
#include "tensortransit/trace.h"

using namespace tensortransit;

#ifndef TENSORTRANSIT_GOLDEN_DIR
#define TENSORTRANSIT_GOLDEN_DIR "tests/golden"
#endif

static int g_failures = 0;
// Counted, and printed on success. A suite that says only "passed" cannot be
// distinguished from one whose checks were all compiled out, and the repo manifest
// used to carry a hand-typed total that nothing regenerated.
static int g_checks = 0;
#define CHECK(cond) do { ++g_checks; if (!(cond)) { \
    std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); ++g_failures; } } while (0)

static std::string golden_path(const char* name) {
    return std::string(TENSORTRANSIT_GOLDEN_DIR) + "/" + name;
}

struct Loaded {
    TensorRegistry registry;
    TransitGraph graph;
    TraceMetadata meta;
    bool ok = false;
};

static Loaded load(const char* name) {
    Loaded out;
    std::string error;
    out.ok = read_trace_file(golden_path(name), &out.registry, &out.graph, &out.meta, &error);
    if (!out.ok) std::printf("FAIL cannot read %s: %s\n", name, error.c_str());
    return out;
}

static TransitPlannerConfig base() {
    // Pinned deliberately. A golden digest computed under whatever the defaults happen to be
    // would change whenever a default changed, which is a different fact from the one this
    // file is asserting.
    TransitPlannerConfig config{};
    config.persist_roles = RoleMask::of(TensorRole::RecurrentState, TensorRole::KVCache);
    // NOT stream_roles. `preset_config` gives those to the GLOBAL arm alone, because telling
    // the weight stream to get out of the way is a coordination action and an arm that could
    // take it would not be the independent policy it is supposed to be. Setting it in the
    // base handed it to every arm, which was invisible only while Stream was unreachable
    // under a cyclic decode graph -- so the harness and the design agreed by accident.
    config.prefetch_roles = RoleMask::none();
    config.prefetch_enabled = false;
    config.budget_fraction = 0.75;
    config.hit_ratio = 0.70;
    config.min_hit_ratio = 0.05;
    config.role_floor_share = 0.25;
    config.reuse_metric = ReuseMetric::Bytes;
    config.admission = AdmissionRule::Density;
    config.window_binding = WindowBinding::PerConsumer;
    // Pinned for the same reason as everything else here: the cost model decides what a plan
    // is predicted to be worth, and one admission rule -- Survival -- decides USING that
    // price, so an unpinned default would move these digests for a reason this file is not
    // about.
    config.cost_model = CostModel::Residency;
    return config;
}

// name -> digest, one "trace/arm 0x..." per line. Missing file means "record", which is how
// a new trace is added; a mismatch is always a failure.
static std::map<std::string, std::string> read_expected() {
    std::map<std::string, std::string> out;
    std::ifstream file(golden_path("plans.golden"));
    if (!file) return out;
    std::string key, value;
    while (file >> key >> value) out[key] = value;
    return out;
}

// The 0.2.0 role_floor sweep, reproduced exactly under `--cost-model linear`.
//
// The linear model is kept as the CONTROL, which is only worth anything if it is still the
// same model. These six figures are what 0.2.0 published in docs/evaluation.md, and they are
// what a contributor comparing a result against "the model this repository used to use" is
// comparing against. A control that had quietly drifted would make every such comparison
// meaningless while looking fine.
static void test_the_linear_control_still_reproduces_the_published_sweep(
        const DeviceProfile& device, int* failures) {
    TensorRegistry registry;
    TransitGraph graph;
    TraceMetadata meta;
    std::string error;
    if (!read_trace_file(golden_path("trace_recurrent_kv.json"), &registry, &graph, &meta,
                         &error)) {
        std::printf("FAIL cannot read trace_recurrent_kv.json: %s\n", error.c_str());
        ++*failures;
        return;
    }
    RuntimeState state{};
    state.active_requests = meta.active_requests;
    parse_runtime_phase(meta.phase.c_str(), &state.phase);
    PlanInput input{&graph, &registry, device, state};

    // (role_floor_share, predicted throughput gain in percent), from docs/evaluation.md as
    // published under 0.2.0.
    static constexpr struct { double share; double gain_pct; } kPublished[] = {
        {0.00, 0.358}, {0.10, 0.349}, {0.25, 0.336},
        {0.50, 0.313}, {0.75, 0.291}, {1.00, 0.269},
    };
    for (const auto& point : kPublished) {
        TransitPlannerConfig config = base();
        config.cost_model = CostModel::Linear;   // the control, explicitly
        config.persist_roles = RoleMask::of(TensorRole::RecurrentState, TensorRole::KVCache);
        config.admission = AdmissionRule::RoleFloor;
        config.role_floor_share = point.share;
        const auto plan = make_budgeted_planner(config)->build_plan(input);
        const double got = (plan.cost().predicted_throughput_ratio() - 1.0) * 100.0;
        // Published to three decimals, so agree to within half of the last one.
        if (std::abs(got - point.gain_pct) > 0.0005) {
            std::printf("FAIL linear control drifted: role_floor_share %.2f published %+.3f%%, "
                        "got %+.5f%%\n", point.share, point.gain_pct, got);
            ++*failures;
        }
    }
}

static std::size_t persist_count(const TransitPlan& plan) {
    std::size_t n = 0;
    for (const TransitAction& action : plan.actions())
        if (action.kind == TransitActionKind::Persist) ++n;
    return n;
}

// A dial that never differs is a dial that misleads.
//
// `AdmissionRule::Survival` prices the WHOLE admitted set with each candidate added and stops
// when the next admission is not worth its share of the reservation. At the FITTED
// beta = 0.1108 that stopping rule never fires and the plan is byte-identical to Density's; a
// little under 0.2 the FIRST candidate stops paying and it admits nothing at all. There is no
// useful middle, and a contributor who selects `--admission survival` expecting a third
// behaviour is entitled to know they got one of the other two.
//
// Pinned rather than described: a change to beta, to the reservation cost or to the stopping
// rule moves this boundary without moving anything a reader would look at.
static void test_survival_is_density_at_the_fitted_beta_and_nothing_above_it(
        const DeviceProfile& device) {
    for (const char* name : {"trace_recurrent.json", "trace_recurrent_kv.json",
                             "trace_concurrency.json"}) {
        Loaded loaded = load(name);
        if (!loaded.ok) { ++g_failures; continue; }
        RuntimeState state{};
        state.active_requests = loaded.meta.active_requests;
        parse_runtime_phase(loaded.meta.phase.c_str(), &state.phase);
        PlanInput input{&loaded.graph, &loaded.registry, device, state};

        TransitPlannerConfig config = base();
        config.persist_roles = RoleMask::of(TensorRole::RecurrentState);

        config.admission = AdmissionRule::Density;
        const auto density = make_budgeted_planner(config)->build_plan(input);
        config.admission = AdmissionRule::Survival;
        const auto survival = make_budgeted_planner(config)->build_plan(input);
        CHECK(persist_count(density) > 0);
        CHECK(density.digest() == survival.digest());

        // Steepen the miss-ratio curve and the stopping rule fires on the first candidate.
        config.residency_beta = 0.30;
        CHECK(persist_count(make_budgeted_planner(config)->build_plan(input)) == 0);
        config.admission = AdmissionRule::Density;
        CHECK(persist_count(make_budgeted_planner(config)->build_plan(input)) > 0);
    }
}

int main(int argc, char** argv) {
    const bool record = argc > 1 && std::strcmp(argv[1], "--record") == 0;
    const std::map<std::string, std::string> expected = read_expected();
    std::ostringstream recorded;

    const char* traces[] = {"trace_recurrent.json", "trace_recurrent_kv.json",
                            "trace_concurrency.json"};
    DeviceProfile device{};
    CHECK(device_profile_by_name("rtx5090", &device));

    test_the_linear_control_still_reproduces_the_published_sweep(device, &g_failures);
    test_survival_is_density_at_the_fitted_beta_and_nothing_above_it(device);

    for (const char* trace_name : traces) {
        Loaded loaded = load(trace_name);
        if (!loaded.ok) { ++g_failures; continue; }
        CHECK(loaded.graph.validate() == nullptr);
        // A trace whose uses name tensors it does not declare would silently shrink the
        // graph, and every digest below would be a digest of the wrong workload.
        CHECK(loaded.graph.unresolved_uses() == 0);

        RuntimeState state{};
        state.active_requests = loaded.meta.active_requests;
        parse_runtime_phase(loaded.meta.phase.c_str(), &state.phase);
        PlanInput input{&loaded.graph, &loaded.registry, device, state};

        for (const PolicyPreset preset :
             {PolicyPreset::Baseline, PolicyPreset::RecurrentOnly, PolicyPreset::KVOnly,
              PolicyPreset::NaiveBothPersistent, PolicyPreset::Global}) {
            const TransitPlannerConfig config = preset_config(preset, base());
            auto planner = make_planner(preset_planner(preset), config);
            if (!planner) { ++g_failures; continue; }
            TransitPlan plan = planner->build_plan(input);
            plan.finalize();

            const char* problem = plan.validate();
            if (problem) std::printf("FAIL %s/%s: %s\n", trace_name, to_string(preset), problem);
            CHECK(problem == nullptr);

            char digest[32];
            std::snprintf(digest, sizeof(digest), "%016llx",
                          static_cast<unsigned long long>(plan.digest()));
            const std::string key = std::string(trace_name) + "/" + to_string(preset);
            recorded << key << " " << digest << "\n";

            const auto it = expected.find(key);
            if (it == expected.end()) {
                if (!record) {
                    std::printf("FAIL no golden digest for %s (run with --record to add it)\n",
                                key.c_str());
                    ++g_failures;
                }
            } else if (it->second != digest) {
                std::printf("FAIL %s: plan changed, golden %s but got %s\n", key.c_str(),
                            it->second.c_str(), digest);
                ++g_failures;
            }
        }

        // The graph's own arithmetic is golden too, and it is the part a planner change must
        // NOT move: a planner that altered the recorded step traffic would be rewriting the
        // denominator of its own score.
        char key[128];
        std::snprintf(key, sizeof(key), "%s/step_traffic_bytes", trace_name);
        char value[32];
        std::snprintf(value, sizeof(value), "%zu", loaded.graph.step_traffic_bytes());
        recorded << key << " " << value << "\n";
        const auto it = expected.find(key);
        if (it != expected.end()) {
            if (it->second != value) {
                std::printf("FAIL %s: step traffic changed, golden %s but got %s\n", key,
                            it->second.c_str(), value);
                ++g_failures;
            }
        } else if (!record) {
            std::printf("FAIL no golden step traffic for %s\n", key);
            ++g_failures;
        }
    }

    // The one arithmetic identity worth pinning by hand, because it is the number the whole
    // project turns on and it is checkable against a figure published before any of this
    // code existed: on Qwen3.8-27B at batch 1, a persisting policy over recurrent state has
    // a ceiling of 0.68% and holds 41% of the footprint. See README, "Concurrency is where
    // the room is". If the graph ever stops reproducing that, the graph is wrong.
    {
        Loaded loaded = load("trace_recurrent.json");
        if (loaded.ok) {
            const CeilingReport report =
                compute_ceiling(loaded.graph, device, RoleMask::of(TensorRole::RecurrentState));
            const double ceiling_percent = (report.bounded_ratio() - 1.0) * 100.0;
            const double resident = report.resident_fraction();
            std::printf("  recurrent persist ceiling %.3f%% at %.1f%% residency"
                        " (published: 0.68%% at 41%%)\n",
                        ceiling_percent, resident * 100.0);
            CHECK(ceiling_percent > 0.66 && ceiling_percent < 0.70);
            CHECK(resident > 0.40 && resident < 0.42);
            // ...and the traffic ceiling, published as 1.69%.
            const double traffic_percent = (report.removable_ratio() - 1.0) * 100.0;
            CHECK(traffic_percent > 1.67 && traffic_percent < 1.71);
        } else {
            ++g_failures;
        }
    }

    if (record) {
        std::ofstream file(golden_path("plans.golden"));
        file << recorded.str();
        std::printf("recorded %s\n", golden_path("plans.golden").c_str());
        return 0;
    }
    if (g_failures) { std::cout << g_failures << " golden check(s) failed\n"; return 1; }
    std::cout << "golden plan tests passed (" << g_checks << " checks)\n";
    return 0;
}
